### ISSUE TITLE
Exception in Graphics2DTester

### ISSUE THREAD

**Issue by jfree** [jfree/fxgraphics2d#12]
When running the Graphics2DTester, after some iterations the following exception is triggered:

```drawTestOutput(FXGraphics2D) duration = 124.77722999999999 ms.
Elapsed: 150.929
FPS: 3.364
java.lang.ClassCastException: class com.sun.prism.paint.Color cannot be cast to class java.lang.String (com.sun.prism.paint.Color is in module javafx.graphics@20-ea of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
        at javafx.graphics@20-ea/com.sun.javafx.sg.prism.NGCanvas.handleRenderOp(NGCanvas.java:1375)
        at javafx.graphics@20-ea/com.sun.javafx.sg.prism.NGCanvas.renderStream(NGCanvas.java:1104)
        at javafx.graphics@20-ea/com.sun.javafx.sg.prism.NGCanvas.renderContent(NGCanvas.java:610)
        at javafx.graphics@20-ea/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
        at javafx.graphics@20-ea/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
        at javafx.graphics@20-ea/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
        at javafx.graphics@20-ea/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
        at javafx.graphics@20-ea/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
        at javafx.graphics@20-ea/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
        at javafx.graphics@20-ea/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
        at javafx.graphics@20-ea/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
        at javafx.graphics@20-ea/com.sun.javafx.sg.prism.NGNode.renderForClip(NGNode.java:2313)
        at javafx.graphics@20-ea/com.sun.javafx.sg.prism.NGNode.renderRectClip(NGNode.java:2207)
        at javafx.graphics@20-ea/com.sun.javafx.sg.prism.NGNode.renderClip(NGNode.java:2233)
        at javafx.graphics@20-ea/com.sun.javafx.sg.prism.CacheFilter.renderNodeToCache(CacheFilter.java:683)
        at javafx.graphics@20-ea/com.sun.javafx.sg.prism.CacheFilter.render(CacheFilter.java:587)
        at javafx.graphics@20-ea/com.sun.javafx.sg.prism.NGNode.renderCached(NGNode.java:2377)
        at javafx.graphics@20-ea/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2063)
        at javafx.graphics@20-ea/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
        at javafx.graphics@20-ea/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
        at javafx.graphics@20-ea/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
        at javafx.graphics@20-ea/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
        at javafx.graphics@20-ea/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
        at javafx.graphics@20-ea/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
        at javafx.graphics@20-ea/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
        at javafx.graphics@20-ea/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
        at javafx.graphics@20-ea/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
        at javafx.graphics@20-ea/com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:480)
        at javafx.graphics@20-ea/com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:321)
        at javafx.graphics@20-ea/com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:92)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
        at javafx.graphics@20-ea/com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at javafx.graphics@20-ea/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:126)
        at java.base/java.lang.Thread.run(Thread.java:1589)
```

**Comment by bourgesl** [comment]
Seems related to renderRectClip()
I will have a look, thx
